language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm-nightly
    - php: 7.0

before_script:
  - composer update --no-interaction --prefer-dist

script:
  - ./vendor/phpunit/phpunit/phpunit -v
