language: php
php:
  - nightly
  - hhvm
  - 7.1
  - 7.0
  - 5.6
  - 5.5

matrix:
  allow_failures:
    - php: nightly

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^[0-9]+[.][0-9]+$ ]]; then phpenv config-rm xdebug.ini; ; echo "memory_limit=2G" >> /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/travis.ini; fi
  - composer self-update
  - composer update --no-interaction --prefer-dist

script:
  - ./vendor/phpunit/phpunit/phpunit -v
