services:
#    drd_plus_cave_tables.example:
#        class: DrdPlus\Cave\TablesBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  drd_plus_cave_tables.tables:
    class: DrdPlus\Tables\Tables
