imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: config-parts/services.yml }
    - { resource: config-parts/doctrine.yml }
    - { resource: config-parts/swiftmailer.yml }
    - { resource: config-parts/assetic.yml }
    - { resource: config-parts/twig.yml }
    - { resource: config-parts/framework.yml }
