drd_plus_cave_tables:
    resource: "@DrdPlusCaveTablesBundle/Resources/config/routing.yml"
    prefix:   /

drd_plus_cave_character:
    resource: "@DrdPlusCaveUnitBundle/Resources/config/routing.yml"
    prefix:   /

