drd_plus_cave_unit_person:
    path:     /person/
    defaults: { _controller: DrdPlusCaveUnitBundle:Person:person }
drd_plus_cave_unit_choice_and_fate:
    path:     /choice-and-fate/
    defaults: { _controller: DrdPlusCaveUnitBundle:Person:choiceAndFate }
drd_plus_cave_unit_exceptionality_properties:
    path:     /exceptionality-properties/
    defaults: { _controller: DrdPlusCaveUnitBundle:Person:exceptionalityProperties }
drd_plus_cave_unit_person_overview:
    path:     /person-overview/
    defaults: { _controller: DrdPlusCaveUnitBundle:Person:personOverview }