services:
  drd_plus_cave_unit.exceptionalities_factory:
    class: DrdPlus\Exceptionalities\ExceptionalitiesFactory
  drd_plus_cave_unit.exceptionality_properties_factory:
    class: DrdPlus\Exceptionalities\Properties\ExceptionalityPropertiesFactory
  drd_plus_cave_unit.base_properties_factory:
    class: DrdPlus\Properties\Base\BasePropertiesFactory
  drd_plus_cave_unit.races_factory:
    class: DrdPlus\Races\RacesFactory
